# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Savelogs
version:      0.11
version_from: lib/Config/Savelogs.pm
installdirs:  site
requires:
    Storable:                      1.014

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
